-- MySQL Script generated by MySQL Workbench
-- Mon Dec 15 10:28:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Dim_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dim_User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `current_age` INT NULL,
  `retirement_age` INT NULL,
  `birth_year` YEAR(4) NULL,
  `birth_month` DATE NULL,
  `gender` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `latitude` DECIMAL(2) NULL,
  `longitude` DECIMAL(2) NULL,
  `per_capita_income` DECIMAL(2) NULL,
  `yearly_income` DECIMAL(2) NULL,
  `total_debt` DECIMAL(2) NULL,
  `credit_score` INT NULL,
  `num_credit_cards` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dim_Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dim_Card` (
  `Dim_Card_id` INT NOT NULL,
  `Dim_User_user_id` INT NOT NULL,
  `card_brand` VARCHAR(45) NULL,
  `card_type` VARCHAR(45) NULL,
  `card_number` INT NULL,
  `expires` DATE NULL,
  `cvv` INT(3) NULL,
  `has_chip` TINYINT NULL,
  `num_cards_issued` INT(3) NULL,
  `credit_limit` DECIMAL(2) NULL,
  `acct_open_date` DATETIME NULL,
  `year_pin_last_changed` YEAR(4) NULL,
  `card_on_dark_web` TINYINT NULL,
  PRIMARY KEY (`Dim_Card_id`, `Dim_User_user_id`),
  INDEX `fk_Dim_Card_Dim_User_idx` (`Dim_User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Dim_Card_Dim_User`
    FOREIGN KEY (`Dim_User_user_id`)
    REFERENCES `mydb`.`Dim_User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fact_Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fact_Transactions` (
  `id` INT NOT NULL,
  `Dim_Card_Dim_Card_id` INT NOT NULL,
  `Dim_Card_Dim_User_user_id` INT NOT NULL,
  `date` DATETIME NULL,
  `amount` DECIMAL(2) NOT NULL,
  `use_chip` VARCHAR(45) NULL,
  `merchant_id` INT NULL,
  `merchant_city` VARCHAR(45) NULL,
  `merchant_state` VARCHAR(45) NULL,
  `zip` INT NULL,
  `mcc` INT(4) NULL,
  `errors` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `Dim_Card_Dim_Card_id`, `Dim_Card_Dim_User_user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Fact_Transactions_Dim_Card1_idx` (`Dim_Card_Dim_Card_id` ASC, `Dim_Card_Dim_User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Fact_Transactions_Dim_Card1`
    FOREIGN KEY (`Dim_Card_Dim_Card_id` , `Dim_Card_Dim_User_user_id`)
    REFERENCES `mydb`.`Dim_Card` (`Dim_Card_id` , `Dim_User_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
